zfsprep_zap_disks: true
zfsprep_root_pool: "{{ zfsprep_hostname.long }}"
zfsprep_efi: true #in the packerfiles, this gets overridden at the command line
zfsprep_hostname:
  short: arc
  long: arc.subly.me
zfsprep_root_disks:
  - sda
  - sdb
zfsprep_root_pool_type: "mirror"
zfsprep_legacy_device_nodes: false
zfsprep_timezone: "America/Detroit"

